(in-package :agent)

(defbehavior look-when-told (:or ((:on (:command :look :from :head))
                                  (:on (:command :look :from :eye)))
                                 :do :invoke-with-event) (organ event)
  (log-for (trace organ) "organ: ~A event: ~A look event" organ event)
  (let* ((thing (getf event :at)))
    (log-for (trace organ) "calling see on ~A with subject: ~A and info: ~A" organ (first thing) (rest thing))
    (apply #'see organ (first thing) thing)))

(defclass watch-mixin ()
  ((watching :initform (make-hash-table :test 'equalp) :accessor watching)))

(defbehavior watch-when-told (:or ((:on (:command :watch :from :head))
                                   (:on (:command :stop-watching :from :head))
                                   (:interval (:from :heart :nth 6)))
                                  :include (watch-mixin)
                                  :do :invoke-with-event) (organ event)
  (log-for (trace organ) "organ: ~A event: ~A watch event" organ event)
  ; (:HEAD :COMMAND :COMMAND :WATCH :WATCH (:PROCESS :PID :PID PID))
  ; (:HEAD :COMMAND :COMMAND :WATCH :WATCH (:PEER :UUID :UUID UUID))
  (case (getf event :command)
    (:watch (watch behavior (getf event :watch)))
    (:stop-watching (stop-watching behavior (getf event :stop-watching)))
    (otherwise (watch-interval behavior))))

(defmethod watch ((behavior watch-mixin) subject)
  (setf (gethash subject (watching behavior)) 0))

(defmethod stop-watching ((behavior watch-mixin) subject)
  (remhash subject (watching behavior)))

(defmethod watch-interval ((behavior watch-mixin))
  (maphash (lambda (k v)
             (log-for (trace organ eye) "watching: ~A => ~A" k v)
             (send-message (behavior-organ behavior) :command `(:command :look :at ,k))
             (setf (gethash k (watching behavior)) (get-internal-real-time)))
           (watching behavior)))
